### ISSUE TITLE
Repository usage?

### ISSUE THREAD

**Issue by EdricChan03** [haggertk/cm_build_stuff#2]
How do I use this repository for building? There's no clear documentation anywhere.

@haggertk Any explanation?

**Comment by Jprimero15** [comment]
Sad :(

**Comment by EdricChan03** [comment]
@haggertk Could I have an update on this?

**Comment by haggertk** [comment]
If you are a developer I am sure you can use this as a reference to figure out something that works for you. This is wholly designed around my workflow.

**Comment by EdricChan03** [comment]
Thanks for replying to this issue! I'll close this.

**Comment by haggertk** [comment]
for record, something like this _should_ work:
$ . build/envsetup.sh
$ mkdir -p .repo/local_manifests
$ curl https://raw.githubusercontent.com/haggertk/cm_build_stuff/lineage-16.0/local_manifest.xml > .repo/local_manifests/tmp.xml
$ repo sync haggertk
$ rm .repo/local_manifests/tmp.xml
$ repo sync
$ ./picks.sh

After that every repo sync will sync picklist and manifest changes. You'll have to re-run the picks each time you sync the overall tree.
